## Lab 1- Intro to Numpy (Ani)

## Lab Objective
NumPy is a powerful Python package for manipulating data with multi-dimensional
vectors. Its versatility and speed makes Python an ideal language for applied and computational
mathematics. In this lab we introduce basic NumPy data structures and operations as a first step to
numerical computing in Python.

The following notebook contains the solution to problems 1-7 from the Intro to Numpy exercise.

In [1]:
import numpy as np #Basic import
import scipy as sy
import matplotlib.pyplot as plt

## Problem 1

In [2]:
import numpy as np

def mat():
    A = np.array([[3, -1, 4], [1, 5, -9]]) # a 2 by 3 matrix
    B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]]) # a 3 by 4 matrix
    return A @ B

mat()


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

## A demonstration of Cayley Hamilton Theorem
The Cayley–Hamilton theorem states that substituting the matrix A for its scalar element in the base ring results in this polynomial returning the zero matrix.


In [3]:
def Cayley():
    A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
    CH = (-1) * (A @ A @ A) + 9 * (A @ A) -15 * A
    return CH

Cayley() #A demonstration of Cayley Hamilton Theorem (The zero matrix is returned.)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Problem 3

## Writing a function w/o using np.array  (a 7 by 7 by 7 product)

Observation helps in this problem. It is easy to recognise that the A matrix here is upper triangular and the tools in this section tell exactly how one needs to go about them and then sequentially going about replacing with 5 in matrix B. Following this chain, one then changes it to an int

In [4]:
def f():
    # Create A
    A = np.ones((7,7))
    A = np.triu(A)
    
    # Create B
    B1 = (-1) * np.ones((7,7))
    B1 = np.tril(B1)   
    B2 = (5) * np.ones((7,7))
    B2 = np.triu(B2, 1)    
    B = B1 + B2 
    
    # Calculate matrix product ABA, BBA, ABB
    p1 = A @ B @ A
    p2 = B @ B @ A
    p3 = A @ B @ B
    # Change data type to np.int64
    p1 = p1.astype(np.int64)
    
    return p1,p2,p3
    
f() # A 7 by 7 matrix

(array([[ -7,  -8,  -3,   8,  25,  48,  77],
        [ -6, -12, -12,  -6,   6,  24,  48],
        [ -5, -10, -15, -14,  -7,   6,  25],
        [ -4,  -8, -12, -16, -14,  -6,   8],
        [ -3,  -6,  -9, -12, -15, -12,  -3],
        [ -2,  -4,  -6,  -8, -10, -12,  -8],
        [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64),
 array([[ -29.,  -64.,  -69.,  -44.,   11.,   96.,  211.],
        [ -23.,  -52.,  -87.,  -92.,  -67.,  -12.,   73.],
        [ -17.,  -40.,  -69., -104., -109.,  -84.,  -29.],
        [ -11.,  -28.,  -51.,  -80., -115., -120.,  -95.],
        [  -5.,  -16.,  -33.,  -56.,  -85., -120., -125.],
        [   1.,   -4.,  -15.,  -32.,  -55.,  -84., -119.],
        [   7.,    8.,    3.,   -8.,  -25.,  -48.,  -77.]]),
 array([[ -77., -119., -125.,  -95.,  -29.,   73.,  211.],
        [ -48.,  -84., -120., -120.,  -84.,  -12.,   96.],
        [ -25.,  -55.,  -85., -115., -109.,  -67.,   11.],
        [  -8.,  -32.,  -56.,  -80., -104.,  -92.,  -44.],
        [   3.,  -1

## Problem 4 (Fancy Indexing)

In [5]:
def f(a):
    fc = np.copy(a) # Use np.copy
    i0 = fc < 0 # Fancy indexing to set negative entries of the copy to zero
    fc[i0] = 0
    return fc

a = np.array([-3, -4, 5, 9, 0])
f(a) # No negative entries

array([0, 0, 5, 9, 0])

## Problem 5 (Block Matrix)

In [6]:
def f():
    A = np.array([[0, 2, 4], [1, 3, 5]])
    
    B = 3 * np.ones((3,3))
    B = np.tril(B)
    
    C = np.diag([-2, -2, -2])

    r1 = np.column_stack((np.zeros((3,3)), A.T, np.eye(3)))
    r2 = np.column_stack((A, np.zeros((2,2)), np.zeros((2,3))))
    r3 = np.column_stack((B, np.zeros((3,2)), C))
    
    block = np.vstack((r1, r2, r3))
                      
    return block
f()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

## Problem 6 (Right Stochastic Matrix)

In [7]:
def f(A):
    
    i, j = np.shape(A)
    sumrow = np.sum(A, axis=1).reshape((j,1))
    rstoc = A / sumrow # Think of it as a markov matrix
    
    return rstoc

A = np.array([[1,9], [1, 1]])
f(A)


array([[0.1, 0.9],
       [0.5, 0.5]])

## Problem 7 (Project Euler and array slicing)

In [8]:
def f():
    grid = np.load("grid.npy")
    
    vMax = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    hMax = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    rdMax = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    ldMax = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
    
    return max(vMax, hMax, rdMax, ldMax)
   
f()

70600674

## Thanks

References:
    
    1. https://docs.scipy.org/doc/numpy/reference/generated/numpy.column_stack.html